In [1]:
import pandas as pd
import csv

import numpy as np
import matplotlib.pyplot as plt


import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [19]:
# notebook para treinar a nn e conferir com a pré-treinada do phylodeep

def load_data_wrapper():
    # Função semelhante ao load_data, porém, o y do training_data
    # agora é um vetor unitário, representando a classificação correta para x.
    # Para o validation_data e test_data, o y é semelhante a função load_data
    # Abrindo o npz_load com as árvores
    data = np.load('C:\\Users\\JPC\Documents\\MESTRADO\\Projeto\\gillespie-2\\deep_learning_dataset_refatorado.npz',allow_pickle=True)
    

    # Abrindo as info de classificação
    with open('C:\\Users\\JPC\\Documents\\MESTRADO\\Projeto\\gillespie-2\\input_classificacao.txt') as f:
        reader = csv.reader(f, delimiter="\t")
        input_class = list(reader)

    # Removendo o header das info de classificação
    input_class.pop(0)

    # Retornando a segunda coluna (coluna referente ao R_nought)
    # e em segunda transformando a lista em um np.array
    R_nought = [sublist[5] for sublist in input_class]
    R_nought = np.array(R_nought)

    transmission_rate = [sublist[1] for sublist in input_class]
    transmission_rate = np.array(transmission_rate)

    infectious_time = [sublist[6] for sublist in input_class]
    infectious_time = np.array(infectious_time)

    vectorized = []
    for n in range(0, len(transmission_rate)):
        vectorized.append([float(transmission_rate[n]), float(infectious_time[n])])

    #R_nought_vector = []
    ##np.array([1, 0]) if i == 1 else np.array([0, 1]) for i in R_nought
    #for i in R_nought:
    #    if i == '1':
    #        R_nought_vector.append([float(1)])
    #        #R_nought_vector.append([1, 0])
    #    else:
    #        #R_nought_vector.append([5, 1])
    #        R_nought_vector.append([float(5)])

    #R_nought_vector = np.array(R_nought_vector)



    training_data = list(zip(data['tree_data'][:20], R_nought[:20], transmission_rate[:20], infectious_time[:20], vectorized[:20]))
    

    #validation_data = list(zip(data['tree_data'][8000:9000], R_nought_vector[8000:9000]))

    test_data = list(zip(data['tree_data'][0:20], R_nought[0:20], transmission_rate[0:20], infectious_time[0:20], vectorized[0:20]))
    
    return training_data, test_data



# Criar o loop do mini-batch e confere os erros
# Tentar pelo tensorflow


In [3]:
# O training data tem 90.000 obsevações, sendo cada observação a árvore de tamanho 402, o R_0, transmission_rate, infectious_time, a lista deles

In [4]:
'''
training_data, test_data = load_data_wrapper()
#x_train = [sublist[0].reshape(-1,1) for sublist in training_data]
x_train = [sublist[0] for sublist in training_data]
y_train = [float(sublist[1]) for sublist in training_data]
testar_formato =  [float(sublist[3]) for sublist in training_data]

x_train = np.asarray(x_train)
y_train = np.asarray(y_train)
testar_formato = np.asarray(testar_formato)
#--------------------
x_test = [sublist[0] for sublist in test_data]

y_test = [float(sublist[1]) for sublist in test_data]

x_test = np.asarray(x_test)
y_test = np.asarray(y_test)
'''

'\ntraining_data, test_data = load_data_wrapper()\n#x_train = [sublist[0].reshape(-1,1) for sublist in training_data]\nx_train = [sublist[0] for sublist in training_data]\ny_train = [float(sublist[1]) for sublist in training_data]\ntestar_formato =  [float(sublist[3]) for sublist in training_data]\n\nx_train = np.asarray(x_train)\ny_train = np.asarray(y_train)\ntestar_formato = np.asarray(testar_formato)\n#--------------------\nx_test = [sublist[0] for sublist in test_data]\n\ny_test = [float(sublist[1]) for sublist in test_data]\n\nx_test = np.asarray(x_test)\ny_test = np.asarray(y_test)\n'

In [20]:
training_data, test_data = load_data_wrapper()

In [21]:
x_train = [sublist[0] for sublist in training_data]
y_train = [float(sublist[3]) for sublist in training_data]
testar_formato =  [float(sublist[3]) for sublist in training_data]

x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

#x_train_normalized = [(tree - min(tree))/(max(tree)-min(tree)) for tree in x_train]
#x_train_normalized = (x_train - min(x_train))/(max(x_train)-min(x_train))


#x_train_normalized = np.asarray(x_train_normalized)

#-------------------------------------------------------------------

x_test = [sublist[0] for sublist in test_data]
y_test = [float(sublist[3]) for sublist in test_data]

x_test = np.asarray(x_test)
y_test = np.asarray(y_test)


In [ ]:
x_train[1]


array([0.        , 6.92476669, 5.34010782, 6.6544203 , 5.08290405,
       6.32028308, 6.13572829, 6.46428102, 5.64283906, 5.4728137 ,
       4.57060468, 6.3571345 , 4.47681855, 6.60884993, 7.01004757,
       6.36521048, 5.60690274, 5.87927215, 5.69064077, 5.79359047,
       5.5943216 , 6.06962854, 6.13451864, 6.68349907, 5.31348943,
       4.68584203, 4.31004568, 6.99244987, 5.97960205, 7.42594184,
       5.28634494, 4.91540775, 6.59503285, 3.95027027, 7.77653459,
       6.87264966, 4.40753557, 4.30439705, 7.97202095, 6.8218925 ,
       6.38424272, 6.53368384, 4.44940322, 4.45333075, 4.73530826,
       4.80950985, 3.66629335, 6.57539827, 5.76462874, 5.5944562 ,
       5.33618587, 6.52400732, 5.9526053 , 4.86609328, 6.43062136,
       6.32285121, 6.04954174, 5.41527917, 5.27670072, 5.80710761,
       5.6429649 , 6.11404707, 4.63295215, 3.84155885, 6.54804585,
       7.51092347, 6.55765704, 7.43004764, 6.10152576, 6.7818029 ,
       6.40068866, 3.27582852, 2.26306667, 6.90030419, 6.37543

In [12]:
modelo_derivado = tf.keras.models.Sequential([
    layers.Input(x_train[0].shape),
    layers.Reshape((201, 2)),
    layers.Conv1D(filters = 50, kernel_size = 3, activation='relu'),
    layers.Conv1D(filters = 50, kernel_size = 10, activation='relu'),
    layers.MaxPooling1D(pool_size=10),
    layers.Conv1D(filters = 80, kernel_size = 10, activation='relu'),
    layers.GlobalAveragePooling1D(),
    layers.Dense(64, activation='elu'),
    layers.Dense(32, activation='elu'),
    layers.Dense(16, activation='elu'),
    layers.Dense(8, activation='elu'),
    layers.Dense(2, activation='elu'),
    layers.Dense(1, activation='linear')
    ])



In [13]:
modelo_derivado.compile(optimizer='adam', loss='MeanAbsolutePercentageError', metrics=['accuracy'])

modelo_derivado.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ reshape (Reshape)               │ (None, 201, 2)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d (Conv1D)                 │ (None, 199, 50)        │           350 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 190, 50)        │        25,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 19, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 10, 80)         │        40,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ (None, 80)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         5,184 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 2)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 73,429 (286.83 KB)

 Trainable params: 73,429 (286.83 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
history = modelo_derivado.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 99.5457 - val_accuracy: 0.0000e+00 - val_loss: 97.8680
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.0000e+00 - loss: 97.9610 - val_accuracy: 0.0000e+00 - val_loss: 96.5255
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.0000e+00 - loss: 96.6531 - val_accuracy: 0.0000e+00 - val_loss: 94.9866
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0000e+00 - loss: 95.1292 - val_accuracy: 0.0000e+00 - val_loss: 93.1105
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0000e+00 - loss: 93.2060 - val_accuracy: 0.0000e+00 - val_loss: 90.7641
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.0000e+00 - loss: 90.7205 - val_accuracy: 0.0000e+00 - val_loss: 87.7771
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0000e+00 - loss: 87.4866 - val_accuracy: 0.0000e+00 - val_loss: 83.9599
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accura

In [11]:
# Como usar o evaluate?
# modelo_derivado.evaluate(x_test, y_test)

In [12]:
y_predict = modelo_derivado.predict(x_train[:20])
y_predict

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


array([[1.2835516],
       [1.2026781],
       [1.279068 ],
       [1.2813556],
       [1.2836611],
       [1.2840234],
       [1.2840788],
       [1.2838132],
       [1.2840846],
       [1.2837622],
       [1.2836986],
       [1.282646 ],
       [1.2805463],
       [1.2805463],
       [1.2838736],
       [1.2840638],
       [1.2840638],
       [1.2840165],
       [1.2802601],
       [1.2802601]], dtype=float32)

In [13]:
y_predict = modelo_derivado.predict(x_test[9980:])
y_predict

c:\Users\JPC\anaconda3\envs\phylodeepenv\lib\contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)


ValueError: math domain error

In [ ]:
y_test[9980:]

array([0.07199942, 0.39200314, 0.3869969 , 0.07099752, 0.36101083,
       0.46403712, 0.48899756, 0.34094783, 0.36603221, 0.450045  ,
       0.31897927, 0.07900142, 0.1499925 , 0.12899897, 0.32404407,
       0.09500285, 0.04800077, 0.13500743, 0.05699954, 0.4950495 ])

In [ ]:
y_predict_discreto = [5 if n>3 else 1 for n in y_predict]
y_predict_discreto = np.asarray(y_predict_discreto).reshape(-1,1)
y_predict_discreto


array([[5],
       [1],
       [1],
       ...,
       [5],
       [1],
       [5]], shape=(10000, 1))

In [ ]:

accuracy = np.where(y_test==y_predict_discreto, True, False)
print(f'A taxa de acerto foi de {np.sum(accuracy)/10000}.')

A taxa de acerto foi de 0.9847.


In [ ]:
resultados = pd.DataFrame(y_test, columns=['y_test'])
resultados['y_predict_discreto'] = y_predict_discreto
resultados['acerto'] = accuracy
resultados['y_predict'] = y_predict
resultados.head()

,y_test,y_predict_discreto,acerto,y_predict
0,5.0,5,True,4.993727
1,1.0,1,True,1.002230
2,1.0,1,True,1.002302
3,5.0,5,True,4.990980
4,1.0,1,True,1.002239


In [ ]:
resultados.query('y_predict > 1.01 and y_predict < 4.99 and acerto == False').head()

,y_test,y_predict_discreto,acerto,y_predict
297,1.0,5,False,4.989597
382,1.0,5,False,4.989485
903,1.0,5,False,4.989435
1335,1.0,5,False,4.989088
1372,1.0,5,False,4.988916


In [ ]:
resultados[~accuracy]

,y_test,y_predict_discreto,acerto,y_predict
65,1.0,5,False,4.992354
137,1.0,5,False,4.990974
182,1.0,5,False,4.990756
239,1.0,5,False,4.990712
297,1.0,5,False,4.989597
...,...,...,...,...
9788,1.0,5,False,4.991968
9874,1.0,5,False,4.988726
9905,1.0,5,False,4.992577
9969,1.0,5,False,4.990398



---



In [15]:
modelo_original = tf.keras.models.load_model('C:\\Users\\JPC\\Documents\\MESTRADO\\Projeto\\gillespie-2\\BD_SMALL_CNN.h5')

modelo_original.summary()

c:\Users\JPC\anaconda3\envs\phylodeepenv\lib\site-packages\keras\src\layers\reshaping\reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
c:\Users\JPC\anaconda3\envs\phylodeepenv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ reshape_1 (Reshape)             │ (None, 201, 2)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 199, 50)        │           350 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 190, 50)        │        25,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 19, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 10, 80)         │        40,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_1      │ (None, 80)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         5,184 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 2)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 73,426 (286.82 KB)

 Trainable params: 73,426 (286.82 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
modelo_original.compile(optimizer='adam', loss='MeanAbsoluteError', metrics=['accuracy'])

In [22]:
x_test.shape

(20, 402)

In [23]:
predica = modelo_original.predict(x_test[:20])
print(predica)

# pegar a do vinicius q estima R_0 e 1/gamma, 
# treinar só pro infectious
# registrar oq ja fizemos
# testar as 100 arvores geradas
# testar com o remove_rate (inversa do infectiuos time)
#-------------------------------------------------------

#~Exportar a arvore e testar no R
#!Gerar as arvores com treegeneratortest no dropbox
#!Gerar com betafixado e varia só o gamma 
#!estudar o gillepsie

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
[[1.237159  2.351757 ]
 [4.99232   5.3709536]
 [1.4205328 2.496621 ]
 [1.1583049 2.2771776]
 [1.0829263 2.15387  ]
 [4.9842286 4.985589 ]
 [1.066731  2.1383193]
 [1.1093969 2.2056127]
 [4.9486804 4.96428  ]
 [4.60709   5.3198123]
 [1.1092093 2.1692243]
 [4.7922635 5.5119486]
 [4.6945724 5.222474 ]
 [1.2163239 2.321057 ]
 [1.2598184 2.4067974]
 [4.94824   5.420623 ]
 [1.0665967 2.1609669]
 [4.5275106 5.4045234]
 [1.1320645 2.225988 ]
 [4.7732606 5.521165 ]]


In [ ]:
import inspect

import phy

print(inspect.getsource(phy.remove_certain_leaves))